abstract class CategoryMoviesScreenStates{}
class InitCategoryMoviesScreenState extends CategoryMoviesScreenStates{}

class LoadingCategoryMoviesScreenState extends CategoryMoviesScreenStates{}
class SuccessCategoryMoviesScreenState extends CategoryMoviesScreenStates{}
class ErrorCategoryMoviesScreenState extends CategoryMoviesScreenStates{}
